const alunos = ["Symon","João","Pedro"];

console.log(alunos);
console.log("------------------------------------------------------------------------------------");
console.log(alunos[0]);
console.log(alunos[1]);
console.log(alunos[2]);
console.log("------------------------------------------------------------------------------------");
alunos.push("Matheus");
console.log(alunos[3]);
console.log("------------------------------------------------------------------------------------");
alunos[4] = "Pietro";
console.log(alunos);
console.log("------------------------------------------------------------------------------------");
const listaAlunos = [];
listaAlunos.push("Teste1");
listaAlunos.push("Teste2");
listaAlunos.push("Teste3");
listaAlunos.push("Teste4");
listaAlunos.push("Teste5");
listaAlunos.push("Teste6");
console.log(listaAlunos);
console.log(listaAlunos.length);
console.log("------------------------------------------------------------------------------------");
listaAlunos.pop();
console.log(listaAlunos);
console.log(listaAlunos.length);
console.log("------------------------------------------------------------------------------------");
listaAlunos.shift();
console.log(listaAlunos);
console.log(listaAlunos.length);
console.log("------------------------------------------------------------------------------------");
